"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "zh-Hant" | "en";

const storageKey = "code-tutor:language";

const translations = {
  "zh-Hant": {
    navHome: "首頁",
    navFiles: "檔案",
    navProblems: "題目",
    navQuiz: "測驗",
    navSettings: "設定",
    comingSoon: "即將推出",
    settings: "設定",
    languageLabel: "語言",
    languageName: "繁體中文",
    languageButton: "切換介面語言，目前為繁體中文",
    accountMenu: "開啟帳號選單",
    account: "帳號",
    guest: "尚未登入",
    signIn: "登入",
    signUp: "建立帳號",
    signOut: "登出",
    forgotPassword: "忘記密碼？",
    backToSignIn: "返回登入",
    displayName: "顯示名稱",
    email: "Email",
    password: "密碼",
    confirmPassword: "再次輸入密碼",
    accountConfiguredMissing: "尚未設定 Supabase 連線資料。",
    accountConfiguredHint: "請先在 frontend/.env.local 加入 Project URL 與 Publishable key。",
    signingIn: "登入中…",
    creatingAccount: "建立帳號中…",
    sendingReset: "寄送中…",
    resetPasswordAction: "寄送重設密碼信",
    resetEmailSent: "重設密碼信已寄出，請檢查信箱。",
    confirmationEmailSent: "帳號已建立，請到信箱完成 Email 確認。",
    passwordMismatch: "兩次輸入的密碼不相同。",
    passwordTooShort: "密碼至少需要 8 個字元。",
    signedInAs: "目前登入",
    accountSettings: "帳號設定",
    closeDialog: "關閉視窗",
    updatePasswordTitle: "設定新密碼",
    updatePasswordDetail: "請輸入新的 Code Tutor 登入密碼。",
    newPassword: "新密碼",
    savePassword: "儲存新密碼",
    savingPassword: "儲存中…",
    passwordUpdated: "密碼已更新，可以返回 Code Tutor。",
    invalidRecovery: "密碼復原連結無效或已過期，請重新申請重設密碼信。",
    loadingAccount: "正在驗證帳號…",
    backHome: "返回 Code Tutor",
    mainNavigation: "主要導覽",
    homeTitle: "歡迎來到 Code Tutor",
    homeDetail: "從檔案建立練習專案，或到題目頁尋找下一個程式挑戰。",
    homeEyebrow: "為 C++ 與 Python 學習打造的程式空間",
    homeHeroTitle: "從寫下第一行，到真正理解每一行",
    homeHeroDetail: "在同一個地方管理練習、執行 C++ 或 Python，並透過 AI Tutor 釐清錯誤與思考方向。",
    homePrimaryAction: "開始寫程式",
    homeSecondaryAction: "瀏覽題目",
    homePreviewProject: "練習專案",
    homePreviewStatus: "編譯成功",
    homePreviewOutput: "執行結果",
    homeFeaturesLabel: "核心功能",
    homeFeaturesTitle: "把練習需要的工具放在一起",
    homeFeaturesDetail: "不用在編輯器、編譯網站和筆記之間來回切換，專心處理現在的問題。",
    homeFilesFeatureTitle: "整理每一次練習",
    homeFilesFeatureDetail: "用 Project、資料夾與標籤保存程式，之後能快速找回相同主題。",
    homeCompilerFeatureTitle: "立即執行 C++ 或 Python",
    homeCompilerFeatureDetail: "使用 Text 或 Interactive Console 測試程式，清楚查看編譯與執行結果。",
    homeAiFeatureTitle: "讓 AI 引導思考",
    homeAiFeatureDetail: "分析程式、解釋錯誤或取得提示；預設先協助理解，而不是直接取代作答。",
    homeStepsLabel: "開始使用",
    homeStepsTitle: "三個步驟開始練習",
    homeStepOneTitle: "建立 Project",
    homeStepOneDetail: "在檔案頁建立 C++ 或 Python Project，也可以用資料夾與標籤分類。",
    homeStepTwoTitle: "編寫並執行",
    homeStepTwoDetail: "在編輯器完成程式，選擇輸入方式後按下 Run。",
    homeStepThreeTitle: "理解並改進",
    homeStepThreeDetail: "查看輸出與錯誤，遇到問題時請 AI Tutor 提供解釋或提示。",
    homeReadyTitle: "準備好開始下一次練習了嗎？",
    homeReadyDetail: "從建立第一個 Project 開始，讓每一次嘗試都能被保存、執行與理解。",
    homeReadyAction: "前往我的檔案",
    addFolder: "新增資料夾",
    addProject: "新增專案",
    folderPrompt: "請輸入資料夾名稱",
    projectPrompt: "請輸入新專案名稱",
    unnamedProject: "未命名專案",
    folders: "資料夾",
    projects: "專案",
    yourProjects: "你的專案",
    selectProjectHint: "選擇專案後才會開啟程式編輯器",
    folderType: "資料夾",
    projectType: "程式專案",
    fileRoot: "我的檔案",
    fileSearchLabel: "搜尋檔案或標籤",
    fileSearchPlaceholder: "搜尋名稱、#APCS中高級、#二分搜…",
    fileTagFilter: "檔案標籤篩選",
    itemName: "名稱",
    itemTags: "標籤",
    itemTagsPlaceholder: "例如：#APCS中高級 #二分搜",
    itemTagsHelp: "輸入 # 就會建立標籤，最多 8 個。",
    createFolderTitle: "建立資料夾",
    createProjectTitle: "建立專案",
    editItemTitle: "編輯名稱與標籤",
    create: "建立",
    cancel: "取消",
    saveChanges: "儲存修改",
    editItem: "編輯",
    deleteItem: "刪除",
    fileLoading: "正在載入你的檔案…",
    signInForFiles: "請先登入，才能建立並保存自己的資料夾與專案。",
    emptyFolders: "這一層還沒有資料夾",
    emptyProjects: "這一層還沒有專案",
    noFileResults: "找不到符合搜尋條件的項目",
    fileStorageNotReady: "Supabase 檔案資料表尚未建立，請先執行 migration。",
    fileLoadFailed: "無法載入檔案，請稍後再試。",
    fileSaveFailed: "無法儲存項目，請檢查名稱是否重複後再試。",
    fileDeleteFailed: "無法刪除項目，請稍後再試。",
    deleteProjectConfirm: "確定要刪除這個專案嗎？此操作無法復原。",
    deleteFolderConfirm: "確定要刪除這個資料夾及其中所有內容嗎？此操作無法復原。",
    deleteProjectTitle: "刪除專案",
    deleteFolderTitle: "刪除資料夾",
    confirmDelete: "確認刪除",
    clearCodeTitle: "清除全部程式碼",
    clearCodeFirstConfirm: "這會清除目前檔案的全部內容。若要繼續，請進行下一次確認。",
    continueClear: "繼續",
    clearCodeFinalTitle: "最後確認",
    clearCodeFinalConfirm: "確定要永久清空目前的 main.cpp 嗎？清除後將立即保存空白內容。",
    confirmClearAll: "全部清除",
    tagCount: "{count} 個標籤",
    fileNavigation: "檔案導覽",
    currentFolders: "這一層的資料夾",
    recentProjects: "最近更新的專案",
    noRecentProjects: "還沒有最近專案",
    currentProject: "目前專案",
    projectFiles: "專案檔案",
    backToFiles: "返回檔案",
    noRecentRuns: "這個專案還沒有執行紀錄",
    dragToMove: "拖曳資料夾或專案，即可移入其他資料夾。拖到「我的檔案」可移回根目錄。",
    dropInFolder: "放開以移入這個資料夾",
    dropInRoot: "放開以移回我的檔案",
    movingItem: "正在移動…",
    fileMoveFailed: "無法移動項目，請確認目標位置沒有同名項目。",
    problemLibrary: "題庫",
    problemHeroTitle: "尋找適合你的練習題",
    problemHeroDetail: "用程度與演算法標籤縮小範圍，快速找到下一題。",
    problemSearchLabel: "搜尋題目或標籤",
    problemSearchPlaceholder: "搜尋題目、#APCS中高級、#二分搜…",
    problemTagFilter: "題目標籤篩選",
    problemList: "題目列表",
    foundProblems: "找到 {count} 題",
    viewProblem: "查看題目 →",
    noProblems: "找不到符合條件的題目",
    clearFilters: "清除搜尋條件",
    history: "歷史紀錄",
    createNewFile: "建立新檔案",
    searchSubmissions: "搜尋提交紀錄",
    recentRuns: "最近執行",
    learningFocus: "學習重點",
    learningFocusDetail: "解二分搜尋題目時，請特別注意邊界條件。",
    yesterday: "昨天",
    aiTutor: "AI 導師",
    coachMode: "引導模式",
    tutorGreeting: "嗨！你的程式已經可以執行。我可以協助你理解結果或找出可能的問題。",
    tutorGreetingNamed: "嗨，{name}！你的程式已經可以執行。我可以協助你理解結果或找出可能的問題。",
    quickActions: "快速操作",
    analyzeCode: "分析程式碼",
    analyzeCodeDetail: "檢查邏輯與程式品質",
    explainError: "解釋錯誤",
    explainErrorDetail: "了解編譯器輸出的訊息",
    giveHint: "給我提示",
    giveHintDetail: "提供方向，但不要直接給答案",
    context: "參考內容",
    contextDetail: "main.cpp 與最新的編譯結果會自動包含在對話中。",
    askCode: "詢問你的程式…",
    sendMessage: "傳送訊息",
    saved: "已儲存",
    saving: "儲存中…",
    saveFailed: "儲存失敗",
    run: "Run",
    running: "Run",
    editorLabel: "main.cpp C++ 程式編輯器",
    spaces: "空格：4",
    output: "輸出",
    input: "輸入",
    problems: "問題",
    clear: "清除",
    clearOutput: "清除輸出",
    standardInput: "標準輸入",
    inputPlaceholder: "輸入程式要讀取的資料…",
    batchInput: "Text",
    interactiveConsole: "Interactive Console",
    consoleWaiting: "按下「Run」以啟動互動式程式。",
    consoleInputPlaceholder: "輸入內容後按 Enter…",
    sendInput: "送出輸入",
    stopProgram: "停止程式",
    consoleConnecting: "正在連線…",
    consoleCompiling: "正在編譯…",
    consoleRunning: "程式執行中",
    consoleStopped: "程式已停止",
    compiling: "正在編譯並執行…",
    noOutput: "程式執行完成，但沒有輸出。",
    outputTruncated: "輸出內容已被安全限制截斷。",
    retryAfter: "大約 {seconds} 秒後再試。",
    pressRun: "按下「Run」以編譯並執行程式。",
    ready: "就緒",
    statusAccepted: "程式執行成功",
    statusCompileError: "編譯失敗",
    statusRuntimeError: "執行階段錯誤",
    statusTimeout: "超過執行時間限制",
    statusUnavailable: "編譯服務目前無法使用",
    statusRateLimited: "執行次數過多，請稍候",
    statusServerBusy: "編譯佇列忙碌中",
    requestTimeout: "編譯請求逾時。",
    cannotReachApi: "無法連線到編譯器 API，請確認 FastAPI 後端已在 8000 埠啟動。",
  },
  en: {
    navHome: "Home",
    navFiles: "File",
    navProblems: "Problems",
    navQuiz: "Quiz",
    navSettings: "Settings",
    comingSoon: "Coming soon",
    settings: "Settings",
    languageLabel: "Language",
    languageName: "English",
    languageButton: "Switch interface language, currently English",
    accountMenu: "Open account menu",
    account: "Account",
    guest: "Not signed in",
    signIn: "Sign in",
    signUp: "Create account",
    signOut: "Sign out",
    forgotPassword: "Forgot password?",
    backToSignIn: "Back to sign in",
    displayName: "Display name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    accountConfiguredMissing: "Supabase connection is not configured yet.",
    accountConfiguredHint: "Add the Project URL and Publishable key to frontend/.env.local first.",
    signingIn: "Signing in…",
    creatingAccount: "Creating account…",
    sendingReset: "Sending…",
    resetPasswordAction: "Send password reset email",
    resetEmailSent: "Password reset email sent. Check your inbox.",
    confirmationEmailSent: "Account created. Check your inbox to confirm your email.",
    passwordMismatch: "The passwords do not match.",
    passwordTooShort: "Password must contain at least 8 characters.",
    signedInAs: "Signed in as",
    accountSettings: "Account settings",
    closeDialog: "Close dialog",
    updatePasswordTitle: "Set a new password",
    updatePasswordDetail: "Enter a new password for your Code Tutor account.",
    newPassword: "New password",
    savePassword: "Save new password",
    savingPassword: "Saving…",
    passwordUpdated: "Your password has been updated. You can return to Code Tutor.",
    invalidRecovery: "This recovery link is invalid or expired. Request a new password reset email.",
    loadingAccount: "Verifying account…",
    backHome: "Back to Code Tutor",
    mainNavigation: "Main navigation",
    homeTitle: "Welcome to Code Tutor",
    homeDetail: "Create a practice project in File, or find your next coding challenge in Problems.",
    homeEyebrow: "A coding space built for learning C++ and Python",
    homeHeroTitle: "From your first line to understanding every line",
    homeHeroDetail: "Manage practice projects, run C++ or Python, and use AI Tutor to make sense of errors and possible approaches—all in one place.",
    homePrimaryAction: "Start coding",
    homeSecondaryAction: "Browse problems",
    homePreviewProject: "Practice project",
    homePreviewStatus: "Build succeeded",
    homePreviewOutput: "Program output",
    homeFeaturesLabel: "Core features",
    homeFeaturesTitle: "Everything you need for focused practice",
    homeFeaturesDetail: "Stay focused on the problem instead of switching between an editor, compiler, and notes.",
    homeFilesFeatureTitle: "Organize every practice session",
    homeFilesFeatureDetail: "Save code with projects, folders, and tags so related topics are easy to find later.",
    homeCompilerFeatureTitle: "Run C++ or Python immediately",
    homeCompilerFeatureDetail: "Test with Text or Interactive Console input and read clear build and runtime results.",
    homeAiFeatureTitle: "Let AI guide your thinking",
    homeAiFeatureDetail: "Analyze code, explain errors, or get a hint. Guidance comes before complete answers.",
    homeStepsLabel: "Get started",
    homeStepsTitle: "Start practicing in three steps",
    homeStepOneTitle: "Create a project",
    homeStepOneDetail: "Create a C++ or Python project in File, then organize it with folders and tags when needed.",
    homeStepTwoTitle: "Write and run",
    homeStepTwoDetail: "Finish your code in the editor, choose an input mode, and press Run.",
    homeStepThreeTitle: "Understand and improve",
    homeStepThreeDetail: "Review output and errors, then ask AI Tutor for an explanation or a useful hint.",
    homeReadyTitle: "Ready for your next practice session?",
    homeReadyDetail: "Create your first project and keep every attempt organized, runnable, and easier to understand.",
    homeReadyAction: "Go to my files",
    addFolder: "New Folder",
    addProject: "New Project",
    folderPrompt: "Enter a folder name",
    projectPrompt: "Enter a new project name",
    unnamedProject: "Untitled Project",
    folders: "Folders",
    projects: "Projects",
    yourProjects: "Your projects",
    selectProjectHint: "The code editor opens after you select a project",
    folderType: "Folder",
    projectType: "Code project",
    fileRoot: "My files",
    fileSearchLabel: "Search files or tags",
    fileSearchPlaceholder: "Search names, #APCSIntermediateAdvanced, #BinarySearch…",
    fileTagFilter: "File tag filters",
    itemName: "Name",
    itemTags: "Tags",
    itemTagsPlaceholder: "Example: #APCSIntermediateAdvanced #BinarySearch",
    itemTagsHelp: "Each # creates a tag, up to 8 tags.",
    createFolderTitle: "Create folder",
    createProjectTitle: "Create project",
    editItemTitle: "Edit name and tags",
    create: "Create",
    cancel: "Cancel",
    saveChanges: "Save changes",
    editItem: "Edit",
    deleteItem: "Delete",
    fileLoading: "Loading your files…",
    signInForFiles: "Sign in to create and save your own folders and projects.",
    emptyFolders: "There are no folders here yet",
    emptyProjects: "There are no projects here yet",
    noFileResults: "No items match your search",
    fileStorageNotReady: "The Supabase file table is not ready. Run the migration first.",
    fileLoadFailed: "Files could not be loaded. Try again later.",
    fileSaveFailed: "The item could not be saved. Check for a duplicate name and try again.",
    fileDeleteFailed: "The item could not be deleted. Try again later.",
    deleteProjectConfirm: "Delete this project? This action cannot be undone.",
    deleteFolderConfirm: "Delete this folder and everything inside it? This action cannot be undone.",
    deleteProjectTitle: "Delete project",
    deleteFolderTitle: "Delete folder",
    confirmDelete: "Delete",
    clearCodeTitle: "Clear all code",
    clearCodeFirstConfirm: "This will remove everything in the current file. Continue to the final confirmation if you still want to clear it.",
    continueClear: "Continue",
    clearCodeFinalTitle: "Are you sure?",
    clearCodeFinalConfirm: "This will permanently clear the current main.cpp.",
    confirmClearAll: "Clear all",
    tagCount: "{count} tags",
    fileNavigation: "File navigation",
    currentFolders: "Folders here",
    recentProjects: "Recently updated projects",
    noRecentProjects: "No recent projects yet",
    currentProject: "Current project",
    projectFiles: "Project files",
    backToFiles: "Back to files",
    noRecentRuns: "This project has no run history yet",
    dragToMove: "Drag a folder or project into another folder. Drop it on My files to move it back to the root.",
    dropInFolder: "Drop to move into this folder",
    dropInRoot: "Drop to move back to My files",
    movingItem: "Moving…",
    fileMoveFailed: "The item could not be moved. Check for an item with the same name in the destination.",
    problemLibrary: "Problem library",
    problemHeroTitle: "Find the right practice problem",
    problemHeroDetail: "Use level and algorithm tags to quickly narrow down your next challenge.",
    problemSearchLabel: "Search problems or tags",
    problemSearchPlaceholder: "Search problems, #APCSIntermediateAdvanced, #BinarySearch…",
    problemTagFilter: "Problem tag filters",
    problemList: "Problem list",
    foundProblems: "{count} problems found",
    viewProblem: "View problem →",
    noProblems: "No problems match your filters",
    clearFilters: "Clear filters",
    history: "History",
    createNewFile: "Create new file",
    searchSubmissions: "Search submissions",
    recentRuns: "Recent runs",
    learningFocus: "Learning focus",
    learningFocusDetail: "Pay close attention to boundary conditions in binary search problems.",
    yesterday: "Yesterday",
    aiTutor: "AI Tutor",
    coachMode: "Coach mode",
    tutorGreeting: "Hi! Your code is ready to run. I can help you understand the result or spot possible problems.",
    tutorGreetingNamed: "Hi {name}! Your code is ready to run. I can help you understand the result or spot possible problems.",
    quickActions: "Quick actions",
    analyzeCode: "Analyze code",
    analyzeCodeDetail: "Review logic and quality",
    explainError: "Explain error",
    explainErrorDetail: "Understand compiler output",
    giveHint: "Give me a hint",
    giveHintDetail: "Get help without the answer",
    context: "Context",
    contextDetail: "main.cpp and the latest compiler output will be included automatically.",
    askCode: "Ask about your code…",
    sendMessage: "Send message",
    saved: "Saved",
    saving: "Saving…",
    saveFailed: "Save failed",
    run: "Run",
    running: "Run",
    editorLabel: "main.cpp C++ code editor",
    spaces: "Spaces: 4",
    output: "Output",
    input: "Input",
    problems: "Problems",
    clear: "Clear",
    clearOutput: "Clear output",
    standardInput: "Standard input",
    inputPlaceholder: "Enter the input your program should read…",
    batchInput: "Text",
    interactiveConsole: "Interactive Console",
    consoleWaiting: "Press Run to start an interactive program.",
    consoleInputPlaceholder: "Type input and press Enter…",
    sendInput: "Send input",
    stopProgram: "Stop program",
    consoleConnecting: "Connecting…",
    consoleCompiling: "Compiling…",
    consoleRunning: "Program running",
    consoleStopped: "Program stopped",
    compiling: "Compiling and running…",
    noOutput: "Program finished without output.",
    outputTruncated: "Output was truncated by the safety limit.",
    retryAfter: "Try again in about {seconds} seconds.",
    pressRun: "Press Run to compile and execute your program.",
    ready: "Ready",
    statusAccepted: "Process finished successfully",
    statusCompileError: "Compilation failed",
    statusRuntimeError: "Runtime error",
    statusTimeout: "Time limit exceeded",
    statusUnavailable: "Compiler service unavailable",
    statusRateLimited: "Too many runs — please wait",
    statusServerBusy: "Compiler queue is busy",
    requestTimeout: "Compiler request timed out.",
    cannotReachApi: "Cannot reach the compiler API. Start the FastAPI backend on port 8000.",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["zh-Hant"];

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("zh-Hant");

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    document.documentElement.lang = nextLanguage;
    try {
      window.localStorage.setItem(storageKey, nextLanguage);
    } catch {
      // The interface still switches when browser storage is unavailable.
    }
  };

  useEffect(() => {
    let restoreTimer: number | undefined;
    try {
      const savedLanguage = window.localStorage.getItem(storageKey);
      if (savedLanguage === "zh-Hant" || savedLanguage === "en") {
        document.documentElement.lang = savedLanguage;
        restoreTimer = window.setTimeout(() => setLanguageState(savedLanguage), 0);
      }
    } catch {
      // Keep Traditional Chinese as the default language.
    }
    return () => {
      if (restoreTimer !== undefined) window.clearTimeout(restoreTimer);
    };
  }, []);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language][key],
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider.");
  return context;
}
